"""update models

Revision ID: 0fab9575775b
Revises: 38822727d142
Create Date: 2024-08-20 15:37:47.096269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fab9575775b'
down_revision = '38822727d142'
branch_labels = None
depends_on = None


def upgrade():
   pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_token', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
