"""update models2

Revision ID: 1686feac4c86
Revises: 0fab9575775b
Create Date: 2024-08-20 15:49:32.402671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1686feac4c86'
down_revision = '0fab9575775b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_token', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
