"""update models3

Revision ID: 1bfe06642406
Revises: 1686feac4c86
Create Date: 2024-08-20 16:02:16.943928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfe06642406'
down_revision = '1686feac4c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_token', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
