"""new model

Revision ID: 38822727d142
Revises: e4f930a1be25
Create Date: 2024-08-19 19:51:02.916196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38822727d142'
down_revision = 'e4f930a1be25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_spotify_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_token', schema=None) as batch_op:
        batch_op.drop_column('user_spotify_id')

    # ### end Alembic commands ###
